### ISSUE TITLE
Unable to find sanitizer called 'x.y'

### ISSUE THREAD

**Issue by ehaivala** [andersinno/django-sanitized-dump#16]
I have a Django 1.8 project for which I'm trying to configure `django-sanitized-dump`. I've followed the steps in readme and read how the imports are resolved but couldn't get the `create_sanitized_dump` command to work properly. All I get is the following `ConfigurationError`:

```
root@2e57134ba7a2:/code# python manage.py create_sanitized_dump > dump.sql
Traceback (most recent call last):
  File "/usr/local/bin/database-sanitizer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/database_sanitizer/__main__.py", line 48, in main
    config = Configuration.from_file(args.config[0])
  File "/usr/local/lib/python3.5/site-packages/database_sanitizer/config.py", line 45, in from_file
    instance.load(config_data)
  File "/usr/local/lib/python3.5/site-packages/database_sanitizer/config.py", line 65, in load
    self.load_sanitizers(config_data)
  File "/usr/local/lib/python3.5/site-packages/database_sanitizer/config.py", line 150, in load_sanitizers
    sanitizer_callback = self.find_sanitizer(sanitizer_name)
  File "/usr/local/lib/python3.5/site-packages/database_sanitizer/config.py", line 230, in find_sanitizer
    name,
database_sanitizer.config.ConfigurationError: Unable to find sanitizer called 'user.first_name'
```

The (dumbed down) project structure is as follows:
```
foobar/
    __init__.py
    forms.py
    models.py
    urls.py
    views.py
sanitizers/
    __init__.py
    generic.py
    user.py
manage.py
.sanitizerconfig
```

**sanitizers/generic.py**
```python
from datetime import datetime
from django.utils import timezone

def sanitize_tz_aware_datetime(value):
    dt = datetime(year=2018, month=1, day=1, hour=12, minute=0, second=0)
    return timezone.make_aware(dt)
```

**sanitizers/user.py**
```python
from faker import Faker

fake = Faker()

def sanitize_email(value):
    return fake.email(domain='example.com')

def sanitize_first_name(value):
    return fake.first_name()

def sanitize_last_name(value):
    return fake.last_name()

def sanitize_username(value):
    return fake.user_name()
```

**.sanitizerconfig** (relevant parts)
```yaml
config:
  addons: []
strategy:
  auth_user:
    date_joined: generic.tz_aware_datetime
    document: null
    email: user.email
    first_name: user.first_name
    groups: null
    id: null
    image: null
    is_active: null
    is_staff: null
    is_superuser: null
    last_login: generic.tz_aware_datetime
    last_name: user.last_name
    logentry: null
    owned_pages: null
    pagerevision: null
    password: null
    user_permissions: null
    username: user.username
    userprofile: null
```

**Comment by frwickst** [comment]
Yeah, the problem is that the `user.name` part does not exist currently. It is just written as an example. With the latest version of `database-sanitizer` that was release today there are some sanitizers build in however, so you can now do `user. sanitize_username` or `user.username` I'm not 100% sure which one will work correctly, try it out :)
These functions were added (might need the `sanitize_` prefix):
```
email
username
full_name_en_gb
given_name_en_gb
surname_en_gb

random_past_timestamp
```

I running `pip install -U database-sanitizer` so that you get these :)

**Comment by ehaivala** [comment]
Adding `sanitize_` prefix has no effect.

Just to clarify the import fails on each one of the sanitizer functions. I.e. if I change all `user.first_name` to `null` it will fail on `generic.tz_aware_datetime` instead and if I replace that one it will fail on one of the remaining functions.

**Comment by frwickst** [comment]
Could it be a pathing issue.. can you try running `database-sanitizer -c .sanitizerconfig postgres://user:password@host/database` ?

**Comment by ehaivala** [comment]
Same error with that one. The issue seems to be related to the underlying`python-database-sanitizer` package instead of this Django wrapper.

**Comment by frwickst** [comment]
It does indeed, mind create a issue there as well pointing to this for instance?

**Comment by ehaivala** [comment]
Sure 👍

**Comment by frwickst** [comment]
Thanks! 👍

**Comment by suutari-ai** [comment]
Fixed long ago in https://github.com/andersinno/python-database-sanitizer/issues/13
